### ISSUE TITLE
苹果移动端无法使用xlab平台

### ISSUE THREAD

**Issue by kelayao** [xiaoZhan-xlab/bigbluebutton#12]
前置条件：
1、老师使用IPAD 浏览器chrome
2、学生使用Iphone 浏览器chrome

测试步骤：
老师和学生登录xlab杭州服务器，进行语音沟通

结果：
移动端使用chrome浏览器进入xlab平台后提示不支持flash，只能使用h5进入平台，进入平台后无法打开麦克风与听到声音

**Comment by hellereye** [comment]
在mac、ios需要安装google chrome或者firefox移动版，苹果自带浏览器不支持
